"""empty message

Revision ID: 049b0075960c
Revises: 7cf3210e8feb
Create Date: 2022-02-02 12:00:38.727390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049b0075960c'
down_revision = '7cf3210e8feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_foods', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'favorite_foods', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite_foods', type_='foreignkey')
    op.drop_column('favorite_foods', 'user_id')
    # ### end Alembic commands ###
