"""empty message

Revision ID: 141801a4c853
Revises: 520f1d6d16f6
Create Date: 2021-11-19 12:43:25.389496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141801a4c853'
down_revision = '520f1d6d16f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_log', 'food_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_log', sa.Column('food_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
