"""empty message

Revision ID: 7cf3210e8feb
Revises: 38ebecdd0b45
Create Date: 2021-11-30 03:04:12.333490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf3210e8feb'
down_revision = '38ebecdd0b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('breakfast_daily_nutrition_goals_id_fkey', 'breakfast', type_='foreignkey')
    op.create_foreign_key(None, 'breakfast', 'daily_nutrition_goals', ['daily_nutrition_goals_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('dinner_daily_nutrition_goals_id_fkey', 'dinner', type_='foreignkey')
    op.create_foreign_key(None, 'dinner', 'daily_nutrition_goals', ['daily_nutrition_goals_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('lunch_daily_nutrition_goals_id_fkey', 'lunch', type_='foreignkey')
    op.create_foreign_key(None, 'lunch', 'daily_nutrition_goals', ['daily_nutrition_goals_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lunch', type_='foreignkey')
    op.create_foreign_key('lunch_daily_nutrition_goals_id_fkey', 'lunch', 'daily_nutrition_goals', ['daily_nutrition_goals_id'], ['id'])
    op.drop_constraint(None, 'dinner', type_='foreignkey')
    op.create_foreign_key('dinner_daily_nutrition_goals_id_fkey', 'dinner', 'daily_nutrition_goals', ['daily_nutrition_goals_id'], ['id'])
    op.drop_constraint(None, 'breakfast', type_='foreignkey')
    op.create_foreign_key('breakfast_daily_nutrition_goals_id_fkey', 'breakfast', 'daily_nutrition_goals', ['daily_nutrition_goals_id'], ['id'])
    # ### end Alembic commands ###
