"""empty message

Revision ID: ad74d52cb131
Revises: 049b0075960c
Create Date: 2022-02-02 23:37:50.121845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad74d52cb131'
down_revision = '049b0075960c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_foods', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('favorite_foods', sa.Column('calories', sa.Integer(), nullable=False))
    op.add_column('favorite_foods', sa.Column('carbohydrates', sa.Integer(), nullable=False))
    op.add_column('favorite_foods', sa.Column('fat', sa.Integer(), nullable=False))
    op.add_column('favorite_foods', sa.Column('protein', sa.Integer(), nullable=False))
    op.drop_constraint('favorite_foods_foodlog_id_fkey', 'favorite_foods', type_='foreignkey')
    op.drop_column('favorite_foods', 'foodlog_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_foods', sa.Column('foodlog_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('favorite_foods_foodlog_id_fkey', 'favorite_foods', 'food_log', ['foodlog_id'], ['id'])
    op.drop_column('favorite_foods', 'protein')
    op.drop_column('favorite_foods', 'fat')
    op.drop_column('favorite_foods', 'carbohydrates')
    op.drop_column('favorite_foods', 'calories')
    op.drop_column('favorite_foods', 'name')
    # ### end Alembic commands ###
